### ISSUE TITLE
AttributeError: module 'msgpack._unpacker' has no attribute 'unpack'

### ISSUE THREAD

**Issue by dixiematt8** [wiseodd/controlled-text-generation#10]
I tried to run  train_vae.py
```
Traceback (most recent call last):
  File "train_vae.py", line 40, in <module>
    dataset = SST_Dataset()
  File "/n/w1-bjayakumar/Others_Models/controlled-text-generation/ctextgen/dataset.py", line 8, in __init__
    self.TEXT = data.Field(init_token='<start>', eos_token='<eos>', lower=True, tokenize='spacy', fix_length=16)
  File "./.conda/envs/py36/lib/python3.6/site-packages/torchtext/data/field.py", line 150, in __init__
    self.tokenize = get_tokenizer(tokenize)
  File "./.conda/envs/py36/lib/python3.6/site-packages/torchtext/data/utils.py", line 12, in get_tokenizer
    spacy_en = spacy.load('en')
  File "./.conda/envs/py36/lib/python3.6/site-packages/spacy/__init__.py", line 15, in load
    return util.load_model(name, **overrides)
  File "./.conda/envs/py36/lib/python3.6/site-packages/spacy/util.py", line 112, in load_model
    return load_model_from_link(name, **overrides)
  File "./.conda/envs/py36/lib/python3.6/site-packages/spacy/util.py", line 129, in load_model_from_link
    return cls.load(**overrides)
  File "./.conda/envs/py36/lib/python3.6/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "./.conda/envs/py36/lib/python3.6/site-packages/spacy/util.py", line 173, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "./.conda/envs/py36/lib/python3.6/site-packages/spacy/util.py", line 156, in load_model_from_path
    return nlp.from_disk(model_path)
  File "./.conda/envs/py36/lib/python3.6/site-packages/spacy/language.py", line 653, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "./.conda/envs/py36/lib/python3.6/site-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "./.conda/envs/py36/lib/python3.6/site-packages/spacy/language.py", line 641, in <lambda>
    self.vocab.from_disk(p) and _fix_pretrained_vectors_name(self))),
  File "vocab.pyx", line 380, in spacy.vocab.Vocab.from_disk
  File "vectors.pyx", line 391, in spacy.vectors.Vectors.from_disk
  File "./.conda/envs/py36/lib/python3.6/site-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "vectors.pyx", line 369, in spacy.vectors.Vectors.from_disk.load_key2row
  File "vectors.pyx", line 370, in spacy.vectors.Vectors.from_disk.load_key2row
  File "./.conda/envs/py36/lib/python3.6/site-packages/msgpack_numpy.py", line 179, in unpack
    return _unpacker.unpack(stream, encoding=encoding, **kwargs)
AttributeError: module 'msgpack._unpacker' has no attribute 'unpack'
```

**Comment by wiseodd** [comment]
I think this is the problem on Spacy.
Could you try the solution provided here? https://github.com/explosion/spaCy/issues/2015
