### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'argmax'

### ISSUE THREAD

**Issue by AlinLaw** [wiseodd/controlled-text-generation#18]
I tried to run  python train_discriminator.py 

But
/home/lab303/anaconda2/envs/py36/bin/python /home/lab303/controlled-text-generation/train_discriminator.py
  0%|          | 0/5000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/lab303/controlled-text-generation/train_discriminator.py", line 164, in <module>
    main()
  File "/home/lab303/controlled-text-generation/train_discriminator.py", line 88, in main
    target_c = torch.argmax(c_gen, dim=1)
AttributeError: module 'torch' has no attribute 'argmax'

Requirements 
1. Python 3.5+
2. PyTorch 0.3
3. TorchText https://github.com/pytorch/text

But

PyTorch 0.3 has no attribute 'argmax'

Help me, please.

**Comment by wiseodd** [comment]
Try changing `line 88` on `train_discriminator.py` to:
`_, target_c = torch.max(c_gen, dim=1)`

I hope this fix your issue in PyTorch 0.3.

**Comment by wiseodd** [comment]
Anyway, I revert the usage of `torch.argmax` so that it will run just fine in 0.3.
https://github.com/wiseodd/controlled-text-generation/commit/a52bb151dae2600b6427d0420e6b298cf23c73c6

**Comment by RichardLee777** [comment]
Thank you for your help. I used max(), but still cannot work. I will try to revert the usage of torch.argmax(), too.

/home/lab303/anaconda2/envs/py36/bin/python /home/lab303/controlled-text-generation/train_discriminator.py
  0%|          | 0/5000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/lab303/controlled-text-generation/train_discriminator.py", line 164, in <module>
    main()
  File "/home/lab303/controlled-text-generation/train_discriminator.py", line 98, in main
    loss_u = F.cross_entropy(y_disc_fake, target_c) + beta*entropy
  File "/home/lab303/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/functional.py", line 1140, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, size_average, ignore_index, reduce)
  File "/home/lab303/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/functional.py", line 1049, in nll_loss
    return torch._C._nn.nll_loss(input, target, weight, size_average, ignore_index, reduce)
RuntimeError: nll_loss(): argument 'target' (position 2) must be Variable, not tuple

**Comment by AlinLaw** [comment]
Thank you so much! "changing line 88 on train_discriminator.py to:
_, target_c = torch.max(c_gen, dim=1)"It works!
