### ISSUE TITLE
when running train_discriminator.py ,occuring cudnn RNN backward can only be called in training mode

### ISSUE THREAD

**Issue by zide05** [wiseodd/controlled-text-generation#24]
Traceback (most recent call last):
  File "train_discriminator.py", line 172, in <module>
    main()
  File "train_discriminator.py", line 140, in main
    loss_G.backward()
  File "/remote-home/yrchen/anaconda3/envs/py37_cuda8/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/remote-home/yrchen/anaconda3/envs/py37_cuda8/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cudnn RNN backward can only be called in training mode

**Comment by pelovett** [comment]
Hey, you can solve this problem by adding:
`model.train()`
to line 152 in file `train_discriminator.py`

The problem is caused by the function call `model.sample_sentence(z, c)` calling `model.eval()` but not calling `model.train()` afterwards.

**Comment by zide05** [comment]
oh，i get this，thank you！


 
---Original---

**Comment by mahimanzum** [comment]
> Hey, you can solve this problem by adding:
> `model.train()`
> to line 152 in file `train_discriminator.py`
> 
> The problem is caused by the function call `model.sample_sentence(z, c)` calling `model.eval()` but not calling `model.train()` afterwards.

this does not solve the issue. same error stays. Any solution??

**Comment by Akhila-Yerukola** [comment]
Replace `x_gen_attr` with `x_gen_attr.detach()` in `train_discriminator.py`. i.e in `model.forward_encoder_embed` and `model.forward_discriminator_embed`

**Comment by shizhediao** [comment]
> Replace `x_gen_attr` with `x_gen_attr.detach()` in `train_discriminator.py`. i.e in `model.forward_encoder_embed` and `model.forward_discriminator_embed`

It works, thanks very much!
